
services:
  keenetic-go-vpn:
    build: .
    container_name: keenetic-go-vpn
    restart: unless-stopped
    volumes:
      - keenetic-go-vpn-data:/data
    ports:
      - "800:8000"
    env_file: ".env"

volumes:
  keenetic-go-vpn-data: